version: '3.8'

services:
  http:
    image: nginx:latest
    container_name: http-1
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    ports:
      - "8080:80"
    depends_on:
      - php
      - db

  php:
    image: php:7.4-fpm
    container_name: php-1
    volumes:
      - ./app:/app

  db:
    image: mysql:5.7
    container_name: db-1
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
